# Generated by Django 5.0.6 on 2025-05-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='table',
            name='department',
        ),
    ]
