# Generated by Django 5.0.6 on 2025-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_table_chef_remove_table_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
